[package]
name = "vibraudio-thread"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true

[profile.release]
opt-level = 1
lto = false

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
# -- App Libs
vibraudio-core = { path = "../../libs/vibraudio-core" }
# -- Tracing
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
# -- Others
derive_more = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.9", features = ["winbase", "processthreadsapi", "avrt"] }

[dev-dependencies]
anyhow = { workspace = true }

[build-dependencies]
cc = "1.2"
