[package]
name = "vibraudio"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true

[[example]]
name = "play"
path = "examples/play.rs"

[features]

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
# -- Core
vibraudio-core = { path = "../../libs/vibraudio-core" }
vibraudio-ringbuffer = { path = "../../libs/vibraudio-ringbuffer" }
vibraudio-mp3 = { path = "../../libs/vibraudio-mp3" }

# -- Tracing
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
# -- Others
derive_more = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
vibraudio-alsa = { path = "../../libs/vibraudio-alsa" }

[target.'cfg(target_os = "windows")'.dependencies]
vibraudio-wasapi = { path = "../../libs/vibraudio-wasapi" }

[dev-dependencies]
anyhow = { workspace = true }

[build-dependencies]
cc = "1.2"
