[package]
name = "vibraudio-wasapi"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true

[profile.release]
opt-level = 1
lto = false

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
# -- App Libs
vibraudio-core = { path = "../../libs/vibraudio-core" }
# -- Tracing
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
# -- Others
derive_more = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.52", features = ["Win32_System_Com"] }

[dev-dependencies]
anyhow = { workspace = true }
ctrlc = "3.5.2"

[build-dependencies]
cc = "1.2"
